# Schema for the configuration files of the IP Login module.

ip_login.settings:
  type: config_object
  label: 'IP login settings'
  mapping:
    address_field:
      type: string
      label: 'IP address field for logging in'